# Generated by Django 3.1.6 on 2021-03-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0002_exporter_app_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_exporters',
            field=models.ManyToManyField(related_name='added_users', through='user.Bucket', to='exporter.Exporter'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stared_exporters',
            field=models.ManyToManyField(related_name='starred_users', through='user.Star', to='exporter.Exporter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
