# Generated by Django 3.1.6 on 2021-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210326_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_token',
            field=models.CharField(max_length=100),
        ),
    ]
