# Generated by Django 3.1.3 on 2021-03-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210326_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_token',
            field=models.CharField(max_length=200),
        ),
    ]
