# Generated by Django 3.1.6 on 2021-03-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(),
        ),
    ]
