apiVersion: v2
appVersion: "v0.40.0"
version: 1.0.1
name: cadvisor
description: Cadvisor Helm chart for Kubernetes
type: application
home: "https://github.com/krakazyabra/microservices/tree/main/charts/cadvisor"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://krakazyabra.github.io/microservices/
keywords:
  - prometheus
  - cadvisor
  - monitoring
sources:
  - https://github.com/google/cadvisor
  - https://github.com/krakazyabra/microservices
maintainers:
  - name: krakazyabra
    email: pronin.egor@gmail.com
