{
 "title": "RDS AWS CloudWatch",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Database Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_maximum"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_rds_cpuutilization_average", "legendFormat": "%" }
   ]
  },
  {
   "title": "Read IOPS ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_rds_read_iops_sum" }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_rds_write_iops_sum" }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "description": "In GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average/1000000000"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average / 1000000000"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "aws_rds_read_latency_average" }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "aws_rds_write_latency_average" }
   ]
  }
 ]
}