{
 "title": "collectd prometheus dashboard",
 "description": "collectd-->prometheus-->grafana dashboard memeory,cpu,network,tcp conns",
 "tags": [
  "Prometheus",
  " host"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(collectd_load_midterm,job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(collectd_load_midterm,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$node\",memory=~\"..*\"})"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$node\",memory=\"used\"})"
    }
   ]
  },
  {
   "title": "Total CPU ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(collectd_cpu_total{instance=\"$node\"} ) by(cpu))"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(collectd_cpu_total{instance=\"$node\"} ) by(cpu)) -avg(sum by (type)(irate(collectd_cpu_total{type='idle',instance=~\"$node\"}[5m]))/ 100 )"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$node\",memory=\"used\"}) / sum(collectd_memory{instance=~\"$node\",memory=~\"..*\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(collectd_cpu_total{instance=~\"$node\"}) by (cpu))) - (avg(sum by (type)(irate(collectd_cpu_total{type='idle',instance=~\"$node\"}[5m]))))/ 100 )* 100) / count(count(collectd_cpu_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Used Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$node\",memory=\"used\"}) / sum(collectd_memory{instance=~\"$node\",memory=~\"..*\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(collectd_cpu_total{instance=~\"$node\"}) by (cpu))) - (avg(sum by (type)(irate(collectd_cpu_total{type='idle',instance=~\"$node\"}[5m]))))/ 100 )* 100) / count(count(collectd_cpu_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "collectd_memory", "legendFormat": "{{memory}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by (type,instance)(sum by (type,instance )(irate(collectd_cpu_total{instance=~\"$node\"}[5m]))) /100)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Load (1m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "collectd_load_shortterm{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Load (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "collectd_load_midterm{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Load (15m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "collectd_load_longterm{instance=\"$node\"}"
    }
   ]
  }
 ]
}