# Generated by Django 3.1.3 on 2020-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporter',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
