# Generated by Django 3.1.3 on 2020-11-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20201123_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='commit_date',
            new_name='date',
        ),
    ]
