# Generated by Django 3.1.3 on 2020-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20201123_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
