# Generated by Django 3.1.6 on 2021-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0002_exporter_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporter',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
