# Generated by Django 3.1.3 on 2021-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0003_exporter_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporter',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
