# Generated by Django 3.2.5 on 2021-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0004_auto_20210329_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_at',
            field=models.DateField(default=1981),
        ),
    ]
