# Generated by Django 3.1.12 on 2021-09-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0004_auto_20210329_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_at',
            field=models.DateField(default='1998-9-8'),
        ),
    ]
