# Generated by Django 3.1.3 on 2021-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
