apiVersion: v2
appVersion: 1.2.2
description: A Helm chart for prometheus node-exporter
name: prometheus-node-exporter
version: 2.0.4
type: application
home: https://github.com/prometheus/node_exporter/
sources:
- https://github.com/prometheus/node_exporter/
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- name: vsliouniaev
- name: bismarck
