{
 "title": "EC2 Cloudwatch Exporter Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "System Check Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_ec2_status_check_failed_sum"
    }
   ]
  },
  {
   "title": "CPU utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_ec2_cpuutilization_average" }
   ]
  },
  {
   "title": "Credit Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_ec2_cpucredit_usage_average"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 8 },
   "targets": [
    { "expr": "aws_ec2_network_out_average" }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "targets": [
    { "expr": "aws_ec2_network_in_average" }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "aws_ec2_disk_read_bytes_average"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "aws_ec2_disk_write_bytes_average"
    }
   ]
  }
 ]
}