apiVersion: v2
appVersion: "0.10.0"
description: A Helm chart for prometheus postgres-exporter
name: prometheus-postgres-exporter
version: 2.3.6
home: https://github.com/prometheus-community/postgres_exporter
sources:
- https://github.com/prometheus-community/postgres_exporter
keywords:
- postgresql
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
type: application
