annotations:
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.kubecost.com
apiVersion: v2
appVersion: 1.85.0
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.85.0
